import type { CircuitState, PaymentStatus, Priority } from '@route402/shared';

/**
 * DESIGN.md §4.1 — the single source for turning binding PRD §8 field
 * values into the plain words a viewer sees. No component hardcodes a
 * right-hand value from that table; they all call through here.
 */

const CAPABILITY_LABELS: Record<string, string> = {
  'text.summarize': 'Summarize text',
  'text.translate': 'Translate text',
  'db.provision': 'Provision database',
  'cloud.provision': 'Provision cloud server',
  'email.provision': 'Provision email service',
};

export function capabilityLabel(capability: string): string {
  return CAPABILITY_LABELS[capability] ?? capability;
}

export function circuitStateLabel(state: CircuitState): string {
  switch (state) {
    case 'closed':
      return 'Live';
    case 'half_open':
      return 'Testing';
    case 'open':
      return 'Paused';
  }
}

export type StatusTone = 'ok' | 'warn' | 'bad' | 'info' | 'neutral';

export function circuitStateTone(state: CircuitState): StatusTone {
  switch (state) {
    case 'closed':
      return 'ok';
    case 'half_open':
      return 'warn';
    case 'open':
      return 'bad';
  }
}

export function paymentStatusLabel(status: PaymentStatus): string {
  switch (status) {
    case 'pending':
      return 'Paying';
    case 'settled':
      return 'Paid';
    case 'failed':
      return 'Payment failed';
    case 'refused':
      return 'Not paid';
  }
}

export function paymentStatusTone(status: PaymentStatus): StatusTone {
  switch (status) {
    case 'pending':
      return 'warn';
    case 'settled':
      return 'ok';
    case 'failed':
    case 'refused':
      return 'bad';
  }
}

/** DESIGN.md §4.5 — the active-weights chip, e.g. "Balanced · price 35% · speed 35% · delivered 30%". Mirrors scorer.ts's WEIGHTS table verbatim. */
export function weightsChipLabel(priority: Priority | undefined): string {
  const p = priority ?? 'balanced';
  const weights: Record<Priority, { price: number; speed: number; delivered: number }> = {
    cost: { price: 65, speed: 10, delivered: 25 },
    speed: { price: 10, speed: 65, delivered: 25 },
    balanced: { price: 35, speed: 35, delivered: 30 },
  };
  const w = weights[p];
  return `${priorityChipName(p)} · price ${w.price}% · speed ${w.speed}% · delivered ${w.delivered}%`;
}

function priorityChipName(priority: Priority): string {
  switch (priority) {
    case 'cost':
      return 'Cheapest';
    case 'speed':
      return 'Fastest';
    case 'balanced':
      return 'Balanced';
  }
}

export function priorityLabel(priority: Priority | undefined): string {
  switch (priority) {
    case 'cost':
      return 'Cheapest';
    case 'speed':
      return 'Fastest';
    case 'balanced':
    case undefined:
      return 'Balanced';
  }
}

/**
 * `ineligibleReason` is a free-form sentence generated by `scorer.ts`
 * (`checkEligibility()`), not an enum — matched by prefix, not equality.
 */
export function ineligibleReasonLabel(reason: string | undefined): string {
  if (!reason) return 'Not considered';
  if (reason.startsWith('circuit open')) return 'Paused right now';
  if (reason.startsWith('exceeds max price')) return 'Over budget';
  if (reason.startsWith('excluded')) return 'Excluded by the request';
  return reason;
}
